name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'liberica'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: |
        mvn clean package

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: target/hospital-queuing-system-v*.jar
        repository: parintorn0/hospital-queuing-system
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true

